projects:
  backend:
    schemaPath: "./backend/src/schema.graphql"
    includes: ["./**/*.graphql"]
    extensions:
      endpoints:
        dev: http://localhost:4000/graphql
        prod: https://9vkow8dtoe.execute-api.eu-west-2.amazonaws.com/dev/graphql
