service:
  name: plant-watering-backend

plugins:
  - serverless-webpack
  # - serverless-dynamodb-local
  - serverless-offline

provider:
  name: aws
  runtime: nodejs10.x
  stage: dev
  region: eu-west-2

functions:
  graphql:
    handler: src/handler.graphqlHandler
    events:
      - http:
          path: graphql
          method: post
          cors: true
      - http:
          path: graphql
          method: get

custom:
  serverless-offline:
    port: 4000

  dynamodb:
    start:
      port: 8000
      inMemory: true
      migrate: true
    # seed: true
    # seed:
    #   test:
    #     sources:
    #       - table: Users
    #         sources: [seed-data/Users.json]
    #       - table: Tweets
    #         sources: [seed-data/Tweets.json]

resources:
  Resources:
    PlantsTable:
      Type: "AWS::DynamoDB::Table"
      Properties:
        TableName: "Plants"
        KeySchema:
          - AttributeName: plantId
            KeyType: HASH
        AttributeDefinitions:
          - AttributeName: plantId
            AttributeType: S
        BillingMode: PAY_PER_REQUEST
